name: "Build and Open PR"

on:
  push:
    branches:
      - 'feature**'
      - develop

env:
  HUGO_VERSION: 0.120.2
  NODE_VERSION: 14

jobs:
  build:
    runs-on: "linux"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursively  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: List files
        run: |
          git submodule sync
          git submodule update
          ls -la

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version:  ${{ env.HUGO_VERSION }}
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ env.NODE_VERSION }}

      - name: Install Node Dependencies
        run: |
          ls -lrt
          npm init -y
          npm install postcss-cli
          npm install postcss
          npm install -D --save autoprefixer
          ls -lrt

      - name: Initialize Sub Modules
        run: |
          ls -ltr
          git submodule add https://github.com/google/docsy.git themes/docsy || echo "Submódulos já existem."
          cd ./themes/docsy
          git checkout 86c70cfa35 || echo "Submódulos já existem."
          git submodule update --init --recursive || echo "Submódulos já inicializados."

      - name: Build
        run: hugo --minify

